import { ChevronRightIcon } from "@chakra-ui/icons"
import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useSelector } from "react-redux"
import type { PostStruct } from "../../typechain-types/contracts/Community"
import Header from "../components/Header"
import { useIsMounted } from "../hooks"
import useLoadContracts from "../hooks/useLoadContract"
import { RootState } from "../state/store"

const Home: NextPage = () => {
  const isMounted = useIsMounted()
  useLoadContracts()

  const contractStore = useSelector((state: RootState) => state.contract)

  const [posts, setPosts] = useState([])

  useEffect(() => {
    async function fetchPosts() {
      const communityContract = contractStore?.community
      if (!communityContract || posts?.length > 0) {
        return
      }

      const posts = await communityContract.fetchPosts()
      setPosts(posts)
    }
    fetchPosts()
  }, [contractStore?.community, posts])

  return (
    <div>
      <Head>
        <title>Web3 Communities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isMounted && <Header />}

      {posts.map((post: PostStruct, index) => {
        return (
          <Link href={`/post/${post.title}`} key={index}>
            <a>
              <div>
                <p>Author: {post.author}</p>
                <p>Title: {post.title}</p>
                <p>Content: {post.content}</p>
                <p>Comments: {post.comments}</p>
                <ChevronRightIcon />
              </div>
            </a>
          </Link>
        )
      })}
    </div>
  )
}

export default Home
