import type { NextPage } from "next"
import Head from "next/head"
import Header from "../components/Header"
import { useIsMounted } from "../hooks"

const Home: NextPage = () => {
  const isMounted = useIsMounted()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isMounted && <Header />}

      <main>Main</main>
    </div>
  )
}

export default Home
